# Input Settings: initialize base input folder names,
# dataset collections
input_settings:
    # Base input directory
    input_dir : "inputs"

    # Subdirectory of inputs that datasets are placed in
    dataset_dir: "datasets"

    # Denotes a list of datasets, each with the following parameters:
    #   name: Name of the dataset. May be used in logging or other
    #       messages written during execution
    #
    #   exprData: scRNA-Seq expression data file. Cells are along the
    #            columns and genes are along the rows.
    #   trueEdges: Name of the refrence network file in the
    #              edge list format. Required.
    datasets:
        - name: "mESC"
          exprData: "mESC_BEELINE.csv"
          trueEdges: "mouse-net.csv"
          
    # Ratio of Negatives:Positives in Training.
    kTrain: 1
    # Ratio of Negatives:Positives in Testing.
    kTest: 1
    #randSeed: [2019, 18282]
    # number k in kFold CV
    kFold: 10
    # Number of times to run the k-fold CV
    # generates random seed for each run internally
    # stores as part of the inputs and ouput name
    nTimes: 1
    # If randSeed is specified, it ignores nTimes!!!
    randSeed: [774]
    # kFold CV type, 'Edge' or 'Node'
    # Edge: Edge CV
    # Node: TF holdout CV
    CVType: 'Edge'    
        
    # Denotes a list of algorithms to run. Each has the following parameters:
    #   name: Name of the algorithm. Must be recognized by the pipeline, see
    #       code for acceptable values
    #
    #   should_run: whether or not to run the algorithm
    #
    #   params: any additional, algorithm-specific parameters
    #       should be specified in the params map for a given algorithm
    #
    algorithms:
          # Graph auto-encoder
        - name: "GAE"
          params:
              encoder: ["GCN","DGCN"]
              decoder: ["IP"] #,"NW","RS"]
              hidden: [2]
              channels: [128]
              epochs: [2000]
              should_run: [True]
              reconnect_disconnected_nodes: [False]



# Output Settings: initialize base output folder names
output_settings:
    # Base output directory
    output_dir: "outputs"
    output_prefix: "mESC"
